#!/bin/bash

# --------------------------------------
# | Created By Bruno Santos (LazyDogg) |
# |  26/01/2025 - 03:13 (GMT -03:00)   |
# --------------------------------------

if [[ $(whoami) != root ]]; then
	echo -e "\033[31;1;4mError! you'll need to be root to make this operation\033[0m"
	echo -e "\033[31;1;4m(Do you type sudo?)\033[0m"
	exit 1
fi


user_name=$USER
path_srv=/etc/systemd/system/update.service
chmod 755 ./update
cp -r ./update /usr/local/bin
os=$(cat /etc/os-release | grep "^NAME=*" | sed  's/NAME="//g' | sed 's/ [^>]*//g')
if [[ $# == 1 && $1 == "--server" ]]; then
	echo "[Unit]" > $path_srv
	echo "Description = A automatic update daemon" >> $path_srv
		if [[ $os == "Debian" ]]; then
			echo "After=networking.service" >> $path_srv
			else
			echo "After=NetworkManager.service" >> $path_srv
		fi
	echo -n >> $path_srv
	echo "[Service]" >> $path_srv
	echo "ExecStart=/bin/bash /usr/local/bin/update" >> $path_srv
	echo "User=root" >> $path_srv
	echo "Restart=always" >> $path_srv
	echo "RestartSec=14400" >> $path_srv # Restart Every 4 hours
	echo -n >> $path_srv
	echo "[Install]" >> $path_srv
	echo "WantedBy=multi-user.target" >> $path_srv
fi
if [[ $# == 0 ]]; then
	echo "[Unit]" > $path_srv
	echo "Description = A automatic update daemon" >> $path_srv
		if [[ $os == "Debian" ]]; then
			echo "After=networking.service" >> $path_srv
			else
			echo "After=NetworkManager.service" >> $path_srv
		fi
	echo -n >> $path_srv
	echo "[Service]" >> $path_srv
	echo "ExecStart=/bin/bash /usr/local/bin/update" >> $path_srv
	echo "User=root" >> $path_srv
	echo -n >> $path_srv
	echo "[Install]" >> $path_srv
	echo "WantedBy=multi-user.target" >> $path_srv
fi
systemctl daemon-reload && systemctl enable --now update.service
